name=input("Enter your word:")
phonenum=input("Enter your phone number:")
a=len(name)
b=name.find("a")
c=name.rfind("k")
d=name.capitalize()
e=name.lower()
f=name.upper()
g=name.isdigit()
h=name.isalpha()
i=phonenum.count("9")

print(f"Length of the word: {a}")
print(f"First occurrence of 'a': {b}")
print(f"Last occurrence of 'k': {c}")
print(f"Capitalized: {d}")
print(f"Lowercase: {e}")
print(f"Uppercase: {f}")
print(f"Is the word numeric? {g}")
print(f"Is the word alphabetic? {h}")
print(f"Number of 9 in the phone number is  {i}")
